version: 2
jobs:
  build:
    working_directory: ~/dimibob
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run:
          name: install-deps
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
